### ISSUE TITLE
Redesign and unify focus style

### ISSUE THREAD

**Issue by ffffffelix** [Jahia/moonstone#993]
All components must have the same focus design to understand when a component is focused

I propose something like or we can create a mixin and add it to all components

```scss
[class*="moonstone-"] {
    &[type="button"],
    &[tabindex]:not([tabindex="-1"]) {
        &:focus-visible {
            border-radius: 4px;
            outline: 2px solid var(--color-accent_light);
            outline-offset: 2px;
        }
    }
}
```
